import type { Metadata } from 'next'
import { Header } from '@/presentation/components'
import '@/presentation/core/reset.modules.scss'
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className={inter.className}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
