name: Test Badge generate
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Tests
        run: npm run test:app:ci

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
          coverage-summary-path: ./app/coverage/coverage-summary.json
