name: Test Badge generate
on: [push]
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: (APP) Test
        run: npm run test:app:ci

      - name: (APP) Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
          coverage-summary-path: ./app/coverage/coverage-summary.json
          output-folder: ./app/coverage/badges

      - name: (API) Test
        run: npm run test:api:ci

      - name: (API) Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
          coverage-summary-path: ./api/coverage/coverage-summary.json
          output-folder: ./api/coverage/badges
